steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access --secret=shortener-config latest > config.yml

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
